### ISSUE TITLE
Lazy load - store.model() not a function

### ISSUE THREAD

**Issue by yougotashovel** [rematch/rematch#351]
Trying to lazy load/add a model after `const store = init()`

Using the example from the docs: https://rematch.gitbooks.io/rematch/docs/api.html
`store.model({ name: 'countB', state: 99 })`

Currently getting this error: 
`TypeError: store.model is not a function`

If i inspect the store in the console, i see there's no method for model on the store object either.

**Comment by ShMcK** [comment]
I see it's not working with v0.6. 

Perhaps try using v1.0.0-alpha.2. [Example](https://codesandbox.io/s/0pj982653w)

**Comment by yougotashovel** [comment]
Updated to @next, not getting the error anymore, but it's not activating a new model either.

Can see the same issue here:
https://codesandbox.io/s/3x4l0pnpk6

**Comment by ShMcK** [comment]
Seems to definitely be a bug in both v0.6 & v1 alpha.

For the time being, I would recommend not using `store.model`.

**Comment by ShMcK** [comment]
Now the mystery here is why there are many `store.model` tests that are passing, and yet your provided code sandbox example clearly doesn't work.

As an example, the following is passing:

```js
test('should allow both init models & model models', () => {
    const store = init({
      models: {
        app: {
          state: 'Hello, model 1',
        },
      }
    })

    store.model({
      name: 'app2',
      state: 'Hello, model 2',
    })

    expect(store.getState()).toEqual({
      app: 'Hello, model 1',
      app2: 'Hello, model 2'
    })
  })
```

**Comment by NekR** [comment]
@ShMcK the code example actually works for me and `store.model()` works for me as well in the project, but doesn't work for other people on other machines. Seems weird.

**Comment by NekR** [comment]
Oh, I know what's going on. It doesn't work when Redux DevTools extension is installed.

**Comment by ShMcK** [comment]
Interesting, I'll look into this today.

**Comment by glimow** [comment]
@ShMcK any update on this ? With my team we are very excited about migrating from redux to rematch, but our project heavily relies on lazy loading, thus we are a bit stuck for now.

**Comment by NekR** [comment]
@ShMcK maybe usage of Redux DevTools shouldn't be enabled by default, at least for production? I believe not everyone uses them.

**Comment by yougotashovel** [comment]
@NekR @ShMcK automatic Redux DevTools was one of the things that drew me to this project initially.  It's the killer feature when developing with redux.  But agree about switched off for production.

**Comment by ShMcK** [comment]
Perhaps we could enable devtools by default, but provide an option to disable devtools.

Certainly devtools should be disabled for production.

**Comment by koss-lebedev** [comment]
I've been debugging this issue and I found that `@@redux/REPLACE` action doesn't get handled on a first try. If we manually dispatch this action again from Redux devtools console, it updates the state and reducers properly.

As it was mentioned above, everything works as expected if Redux devtools is disabled. So if you need to use lazy loading, you can disable devtools by adding this line before initializing a store:

```
window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ = undefined
```

**Comment by ShMcK** [comment]
Thanks @koss-lebedev, I've added the replace call to the store.model function.
