### ISSUE TITLE
Property '..' does not exist on type 'never'

### ISSUE THREAD

**Issue by tomploem** [rematch/rematch#759]
**Describe the bug**
I am building a react app (typescript) and used the examples. All examples use one type "sharks state = number" and i am trying to expand the example with an 'authentication' object. Defining the the model in a "mapDispatch" or "mapState" triggers following error:

**Property 'isAuthenticated' does not exist on type 'never'** 

The error is also triggered when i want request an effects function directly instead of dispatching.

works: dispatch({ type: 'authentication/setIsAuthenticated', payload: true })
does not work : dispatch.authentication.setIsAuthenticated(true)

**To Reproduce**

1. typescript: 3.9.2
2. @rematch/core: 1.4.0
3. react-redux: 7.2.0
4. react + react-dom: 16.8.3

**Expected behavior**
Using object instead of single property on a rematch model should be possible. 

**Desktop (please complete the following information):**
- Browser chrome

**Comment by javaLuo** [comment]
typescript 3.8.3 is work.
3.9.2 error

**Comment by endro-00** [comment]
Thanks, it works now! 

Let me know if you need some help testing if it works again. For now, i did a rewind to 3.8.3

**Comment by mtt87** [comment]
Same issue, works with 3.8.3 but not with 3.9.2, the problem seems to be `never` here:
```ts
export type ExtractRematchDispatchersFromModels<M> = {
	[modelKey in keyof M]: M[modelKey] extends ModelConfig ? ExtractRematchDispatchersFromModel<M[modelKey]> : never
}
```

Not sure how to solve it, first time I see `never` being used 👀

**Comment by semoal** [comment]
Hi mate, could you give a try to our next version? We fixed all the issues with typescript typings.

```bash
npx update-by-scope -t next @rematch
````
I added a pinned issue where you can report all the things you find, or create individual issues with the label v2.

**Comment by tomploem** [comment]
Works like a charm 👌 Thanks for providing an update on the issue!

**Comment by kahlan88** [comment]
Still doesn't work, I'm using 
```
   "@rematch/core": "^2.2.0",
    "@rematch/select": "^3.1.2",
```

and getting the same error. I thought a fix for this was merged in 2020. Has it been reverted since?

**Comment by semoal** [comment]
Create a reproducible error and we could help
