### ISSUE TITLE
effect's rootState vs redux-thunk's getState 

### ISSUE THREAD

**Issue by glimow** [rematch/rematch#464]
When using redux-thunk, your async actions have a `getState()` parameter to know about the current state. In rematch, `rootState` is not a function but an object, thus it can be outdated when using several reducers in the same effect.
```javascript
effects: (dispatch)=>({
    async fetch(payload, rootState){
          await dispatch.model.someReducer(payload);
          //rootState is still the old state here 
    },
})
```
 Since `rematch 1.0.0` it is not possible to import global `getState()` and importing store's `getState()` would make a circular dependency as we are in a model.
Is dispatching several actions in one effect a bad practice ? Or is there a workaround ? Why not passing both `dispatch` and `getState` to the effects function, and remove `rootState` ?

**Comment by ShMcK** [comment]
You raise a good point. If there is a possibility of getting the wrong state, `rootState` may be a bad idea.

Internally, rootState is created by a `getState()` call and passed in as a param when the effect is processed. Have you seen it have the wrong value? If it can be demonstrated, we definitely need to make a change.

---

## Alternatives

I can think of a few alternatives to removing getState that you might find useful.

### Import `getState`

It's possible to import `getState` within an effect. 

```js
import { getState } from './store'

export default {
  effects: (dispatch)=>({
    async fetch(payload){
         console.log(getState())
          await dispatch.model.someReducer(payload);
          //rootState is still the old state here 
    },
  })
}
```

### PR to effects function

It may even make more sense to add `getState` as a second param.

```js
 effects: (dispatch, getState)=>({
```

I'd be happy to accept any PR that adds `store.getState` as the second option.

**Comment by jackwilsdon** [comment]
I like the idea of passing `getState` as a second argument - it more closely follows how `redux-thunk` works.

**Comment by glimow** [comment]
@ShMcK I just ran on several cases where rootState had the wrong value when migrating from redux-thunk code to rematch. I guess that's because in redux, state is treated as immutable and is replaced at each dispatch.

I tried your first solution, but that made a circular dependency, model=>store=>model and store resolved to `undefined`. At least I guess because I couldn't find any other explanation for it.

Second solution definitely looks nice and smooth. Will try to do a PR for it.

**Comment by slashwhatever** [comment]
How did this issue die? Never implemented?

**Comment by pjamrozowicz** [comment]
It was never implemented but it could be a nice addition to the v2 PR if someone wants to join me in improving rematch:
https://github.com/rematch/rematch/pull/720

A few places would need to be updated:
- the code itself
- tests
- examples
- documentation
